version: '3.9'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laboop_api
    restart: always
    ports:
      - "5000:8080"
    environment:
      # Database & Redis
      - ConnectionStrings__DB=Server=172.17.0.1,1433;Database=LabOopChange_v6;User Id=sa;Password=Manheno1;Encrypt=False;TrustServerCertificate=True;
      - ConnectionStrings__Redis=188.166.212.41:6379,password=Manheno1

      # JWT
      - JwtSettings__Secret=THIS_IS_SUPER_SECRET_KEY_1234567890
      - JwtSettings__Issuer=LabOOPSystem
      - JwtSettings__Audience=LabOOPUsers
      - JwtSettings__ExpireMinutes=60

      # Google OAuth
      - GoogleAuth__ClientId=41594915925-n7hce257v5uk1fcepfa74qv91jeo15ia.apps.googleusercontent.com

      # Docker UID/GID
      - Docker__UID=1000
      - Docker__GID=1000

    depends_on:
      - java-sandbox

  java-sandbox:
    build:
      context: ./LabAssistantOPP_LAO.Services/Interfaces/Grading/grading-system/java-sandbox
      dockerfile: Dockerfile
    container_name: java_sandbox
    restart: always
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /app/worker_temp:/app/worker_temp
    command: tail -f /dev/null
